### ISSUE TITLE
Implement programs for payload experiments on-orbit

### ISSUE THREAD

**Issue by mryall-mawson** [mawson-rovers/hestia#50]
Create a new binary `uts-run` that does the following:

* Read `uts-programs.toml` config file with the programs and run order from the spreadsheet linked in #42
* Set up a state machine with a state for each program instance, and transitions based on the criteria for each program
* Periodically check if the conditions are met (time, temperature, etc) and move through the state machine accordingly.

Also consider whether to implement temperature abort in firmware rather than software.

**Comment by mryall-mawson** [comment]
Tested and working on two boards. See dashboard screenshot below.

![Screenshot 2023-07-18 at 2 33 02 pm](https://github.com/mawson-rovers/hestia/assets/95326985/5a0002b6-8c0e-4ed4-b38c-6dbe6488a8e2)

Configuration is deployed in `~/uts/uts-programs.toml` on B4, and looks like this:

```toml
loop = false

[[programs]]
heat_board = "Bottom"
heat_time = "60s"
heat_duty = 1.0
temp_sensor = "TH1"
temp_abort = 90.0
thermostat = 80.0
cool_time = "1m 30s"

[[programs]]
heat_board = "Bottom"
heat_time = "30s"
heat_duty = 0.5
temp_sensor = "J7"
temp_abort = 60.0
cool_time = "60s"

[[programs]]
heat_board = "Top"
heat_time = "60s"
heat_duty = 1.0
temp_sensor = "TH1"
temp_abort = 90.0
thermostat = 80.0
cool_time = "1m 30s"
```

Currently programs can only be run from the command line. Configuring and running them via the web interface will be another task.
